config/routes.rb
Rails.application.routes.draw do
 
  get 'password_resets/new'

  get 'password_resets/edit'

root "pages#show", page: "home"
get "/pages/:page" => "pages#show"
get "/pages/home", to: "pages#home", as: "home"
get "/pages/demo", to: "pages#demo", as: "demo"
get "/pages/plan", to: "pages#plan", as: "plan"
get "/pages/browse", to: "pages#browse", as: "browse"
get "/pages/add", to: "pages#add", as: "add"
get "/pages/about", to: "pages#about", as: "about"
get "/login", to: "sessions#new", as: "login"
post "/login", to: "sessions#create"
delete '/logout', to: "sessions#destroy"
get "/signup", to: "users#new", as: "signup"
post '/signup', to: 'users#create'
resources :users
resources :account_activations, only: [:edit]
resources :password_resets, only: [:edit, :create, :new, :update]

end

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<center>
<h1> About AddVenture </h1> 
<%= image_tag("about_me.png", :alt=>"mountains") %>
	<p align="justify">
		<b>AddVenture</b> is a project started in May 2016 by Monique Mezher (yes, that's her above), who at the time had a little to much stress on her plate and not enough adventure to taste. As you can see above, that has changed.

		Monique is currently working on AddVenture on weekends and in her spare time between her Computer Science and Materials Science Engineering classes at the University of Virginia. Her goal is to create a dynamically changing road trip service, able to account for future users adventures and locations recommended by National Park Services, restaurants, and different hole-in-the-wall legends. 

		To do this, Monique is currently working on adding implementation to the Google Map gem. Don't worry if the site isn't ready to give you the perfect road trip, yet- it is coming! 

		For now, you can get <%= link_to "Back to Home", home_path %> and patiently wait for more updates! 
	</p>
</center>

app/views/pages/demo.html.erb
<% provide(:title, "East Coast Dream") %>
<center> 

		<p> East Coast Dream <b> by <u> foobar2016 </u> </b> </p>
<%= image_tag("demo_image.png", :size =>"443x488", :alt=> "map display") %>
</br> </br> </br>
<b>Rating: </b><%= image_tag("stars.png", :size=>"225x35", :alt=> "rating")%>
</center>
<br> 
<center>
<p> <ol> <b> Adventure Breakdown </b> </ol> <p>
<ol>1. Boston, Massachussets. Places to visit include:
	<ul> <u> Barney's Tavern </u> </ul>
	<ul> <u> Harvard Stadium </u></ul>
</ol>
<ol>2. New York, New York. Places to visit include:
	<ul> <u> World Observatory Center </u></ul>
	<ul> <u> Times Square </u></ul>
</ol>
<ol>3. Philadelphia, Pennsylvania. Places to visit include:
	<ul> <u> The Liberty Bell </u></ul>
	<ul> <u> Phil's Cheesesteak Deli </u> </ul>
</ol>
<ol>4. Rohobek Beach, Deleware. Places to visit include:
	<ul> <u> Jason's Shake Shop </u> </ul>
</ol>
<ol>5. Richmond, Virginia. Places to visit include:
	<ul> <u>Sandy's Swing Shack </u> </ul>
	<ul> <u>Virginia Commonwealth Stadium </u> </ul>
	<ul> <u>Grand Forest Hills </u> </ul>
</ol>
<ol>6. Virginia Beach, Virginia. Places to visit include:
	<ul> <a href= "https://www.google.com/maps/place/Mount+Trashmore+Park/@36.8302199,-76.1226688,15z/data=!4m2!3m1!1s0x0:0xec200c9df04ae457?sa=X&sqi=2&ved=0ahUKEwjcz7vboJ3PAhXLNj4KHSzQC4oQ_BIIhQEwDg" target="_blank"><u>Mount Trashmore </u> </a></ul>
	<ul> <u>The Boardwalk </u> </ul>
	<ul> <u>King Trident's Monument </u> </ul>
</ol>
</br>
</br>
<p> <b>Total cost evaluation: </b></br> 
	$100.00 gas + $70.00 food + $350.00 hotel = $520.00 
	</br> 
	<b>Time spent on trip: </b> </br>
	5 days total
</br>

</center>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<div class="center jumbotron">
<h1>
 Welcome. 
</h1>
<a href="signup" class = "btn btn-lg btn-primary"> Begin your adventure </a>
</div>
<div class= "image_one jumbotron">
	<a href="about" class = "btn btn-tug btn-lg btn-primary"> About</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	<a href="plan" class = "btn  btn-tug  btn-lg btn-primary"> Plan Your Trip</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	
	
</div>
</center>

app/views/pages/login.html.erb
<% provide(:title, "Login") %>
<h2><b> login page</b> </h2>

<body>
	Don't have an account? <%= link_to "Sign up", signup_path %>
<%= link_to "Back to Home", home_path %>