config/routes.rb
Rails.application.routes.draw do
 
  get 'password_resets/new'

  get 'password_resets/edit'

root "pages#show", page: "home"
get "/pages/:page" => "pages#show"
get "/pages/home", to: "pages#home", as: "home"
get "/pages/demo", to: "pages#demo", as: "demo"
get "/pages/plan", to: "pages#plan", as: "plan"
get "/pages/browse", to: "pages#browse", as: "browse"
get "/pages/add", to: "pages#add", as: "add"
get "/pages/about", to: "pages#about", as: "about"
get "/login", to: "sessions#new", as: "login"
post "/login", to: "sessions#create"
delete '/logout', to: "sessions#destroy"
get "/signup", to: "users#new", as: "signup"
post '/signup', to: 'users#create'
resources :users
resources :account_activations, only: [:edit]
resources :password_resets, only: [:edit, :create, :new, :update]

end

app/views/layouts/_footer.html.erb
<footer class = 'footer'>
	<small>
		<center>
			AddVenture is the property of Monique Mezher. Copyright 2016. Website created from inspiration by 
			<a href "http://www.railstutorial.org/"> Rails Tutorial made by Michael Hart 
			</a>
		 </center>
	</small>

app/views/layouts/_navbar.html.erb

<nav class="navbar  navbar-inverse ">
		<div class="container-fluid">
			<div class = "navbar-header">
				<button type = "button" class="navbar-toggle" data-toggle="collapse" data-target= "#myNavbar">	
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<li><%= link_to image_tag("add_logo.gif", :border => 0, :alt => "", :title => "", :size => "100x40"), home_path, id:"logo" %></li>	
			</div>
			<div class= "collapse navbar-collapse navbar-left" id="myNavbar">
				<ul class= "nav navbar-nav navbar-center">
					<li><%= link_to "Add a Trip", add_path %> </li>
					<li> <%= link_to "About Addventure", about_path %> </li>
					<li> <%= link_to "Plan", plan_path %> </li>
					<li> <%= link_to "Search", browse_path %> </li>
					<% if logged_in? %>
					<li> <%= link_to "Users", users_path %></li>
					<li class= "dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "My Profile", current_user %></li>
							<li> <%= link_to "Settings", edit_user_path(current_user) %> </li>
							<li class = "divider"></li>
							<% end %>
				</ul>
			</li>
			
				<% if logged_in? %>
					<ul class = "nav navbar-nav navbar-right nav-login">
					<li> <%= button_to "Logout", logout_path , id:"login-nav", :method => "delete" %></li>
				</ul>
				<% else %>
				<ul class = "nav navbar-nav navbar-right nav-login">
					<li> <%= button_to "Login", login_path , id:"login-nav", :method => :get %></li>
				</ul>
				<% end %>
			</nav>
		</div>
	</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= base_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class= "container">
		<div class = "flashing">
	<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %> </div> </div>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>